import { afterEach, describe, expect, it } from "vitest";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { syncGeneratedFiles } from "./sync-ipc.mjs";

const roots = [];
const generated = (name) =>
  `// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.\n\nexport type ${name} = string;\n`;

function fixture() {
  const root = mkdtempSync(join(tmpdir(), "wasabipad-sync-test-"));
  roots.push(root);
  const source = join(root, "source");
  const target = join(root, "target");
  mkdirSync(source);
  mkdirSync(target);
  return { source, target };
}

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe("Feature: syncGeneratedFiles", () => {
  // Given: source/targetに同一`Current.ts`とtargetだけに`Stale.ts`
  // When: `syncGeneratedFiles`を呼ぶ
  // Then: Currentのmtimeは不変、Staleの読み込みは失敗する
  it("Scenario: 同一生成物には触れず、古い生成物だけ削除する", async () => {
    const { source, target } = fixture();
    const current = generated("Current");
    writeFileSync(join(source, "Current.ts"), current);
    writeFileSync(join(target, "Current.ts"), current);
    writeFileSync(join(target, "Stale.ts"), generated("Stale"));
    const before = statSync(join(target, "Current.ts")).mtimeMs;
    await new Promise((resolve) => setTimeout(resolve, 10));

    syncGeneratedFiles(source, target);

    expect(statSync(join(target, "Current.ts")).mtimeMs).toBe(before);
    expect(() => readFileSync(join(target, "Stale.ts"))).toThrow();
  });
});
