import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = resolve(import.meta.dirname, "..");

function generatedFiles(directory) {
  return readdirSync(directory, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".ts"))
    .map((entry) => join(entry.parentPath, entry.name));
}

export function syncGeneratedFiles(sourceDirectory, targetDirectory) {
  const sources = generatedFiles(sourceDirectory);
  const generated = new Set(sources.map((source) => relative(sourceDirectory, source)));
  if (existsSync(targetDirectory)) {
    for (const target of generatedFiles(targetDirectory)) {
      const relativePath = relative(targetDirectory, target);
      if (generated.has(relativePath)) continue;
      const contents = readFileSync(target, "utf8");
      if (!contents.startsWith("// This file was generated by [ts-rs]")) continue;
      rmSync(target);
    }
  }
  for (const source of sources) {
    const target = join(targetDirectory, relative(sourceDirectory, source));
    if (existsSync(target) && readFileSync(source).equals(readFileSync(target))) continue;
    mkdirSync(dirname(target), { recursive: true });
    copyFileSync(source, target);
  }
}

function camelCase(value) {
  return value.replace(/_([a-z])/g, (_match, letter) => letter.toUpperCase());
}

function syncCommandNames(targetDirectory) {
  const backend = readFileSync(join(root, "src-tauri", "src", "main.rs"), "utf8");
  const commands = [...backend.matchAll(/#\[tauri::command\]\s*\r?\n(?:async\s+)?fn\s+(\w+)/g)]
    .map((match) => match[1]);
  const keys = new Set();
  const entries = commands.map((command) => {
    const key = camelCase(command);
    if (keys.has(key)) throw new Error(`IPC command key collision: ${key}`);
    keys.add(key);
    return `  ${key}: "${command}",`;
  });
  const contents = [
    "// This file was generated from src-tauri/src/main.rs by scripts/sync-ipc.mjs.",
    "export const IPC_COMMANDS = {",
    ...entries,
    "} as const;",
    "",
  ].join("\n");
  const target = join(targetDirectory, "IpcCommands.ts");
  mkdirSync(targetDirectory, { recursive: true });
  if (!existsSync(target) || readFileSync(target, "utf8") !== contents) writeFileSync(target, contents);
}

function exportPackage(packageName, exportDirectory) {
  const result = spawnSync(
    "cargo",
    ["test", "-p", packageName, "export_bindings_", "--", "--test-threads=1"],
    {
      cwd: root,
      env: {
        ...process.env,
        TS_RS_EXPORT_DIR: exportDirectory,
        TS_RS_LARGE_INT: "number",
      },
      stdio: "inherit",
    },
  );
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(`${packageName}のIPC型生成に失敗しました`);
}

function main() {
  const exportDirectory = mkdtempSync(join(tmpdir(), "wasabipad-ipc-"));
  try {
    exportPackage("wasabipad-core", exportDirectory);
    exportPackage("wasabipad", exportDirectory);
    syncGeneratedFiles(exportDirectory, join(root, "ui", "generated"));
    syncCommandNames(join(root, "ui", "generated"));
  } finally {
    rmSync(exportDirectory, { recursive: true, force: true });
  }
}

if (resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) main();
