export const INLINE_PREVIEW_MESSAGES = {
  READY_MESSAGE: "wasabipad-viewer-ready",
  PAYLOAD_MESSAGE: "wasabipad-viewer-payload",
  FORMAT_CHANGE_MESSAGE: "wasabipad-viewer-format-change",
  DELIMITER_MESSAGE: "wasabipad-viewer-delimiter",
  DELIMITER_CHANGE_MESSAGE: "wasabipad-viewer-delimiter-change",
  FONT_MESSAGE: "wasabipad-viewer-font",
  FONT_SIZE_MESSAGE: "wasabipad-viewer-font-size",
  MARKDOWN_SOFT_BREAKS_MESSAGE: "wasabipad-viewer-markdown-soft-breaks",
  FONT_CHANGE_MESSAGE: "wasabipad-viewer-font-change",
  FULLSCREEN_CHANGE_MESSAGE: "wasabipad-viewer-fullscreen-change",
  FULLSCREEN_STATE_MESSAGE: "wasabipad-viewer-fullscreen-state",
  SELECTION_CHANGE_MESSAGE: "wasabipad-viewer-selection-change",
  MARKDOWN_LINK_MESSAGE: "wasabipad-viewer-markdown-link",
  MARKDOWN_FRAGMENT_MESSAGE: "wasabipad-viewer-markdown-fragment",
} as const;
